export enum PermissionModule {
  ADMIN = 'ADMIN',
  ADMIN_LIST = 'ADMIN_LIST',
  ADMIN_ROLE_PERMISSIONS = 'ADMIN_ROLE_PERMISSIONS',

  SETTING = 'SETTING',
  SETTING_SMTP = 'SETTING_SMTP',

  APPLICATION_USER = 'APPLICATION_USER',
  APPLICATION_USER_LIST = 'APPLICATION_USER_LIST',

  LOGS = 'LOGS',
  ACTIVITY_LOGS = 'ACTIVITY_LOGS',
  AUDIT_LOGS = 'AUDIT_LOGS',
}
